name: cognoma-machine-learning
dependencies:
- anaconda::dask=0.14.3
- anaconda::jupyter=1.0.0
- anaconda::numexpr=2.6.2
- anaconda::numpy=1.13.0
- anaconda::pandas=0.20.2
- anaconda::python=3.5.3
- anaconda::requests=2.14.2
- anaconda::scikit-learn=0.18.1
- anaconda::scipy=0.19.0
- anaconda::seaborn=0.7.1
- anaconda::setuptools=27.2.0
- anaconda::statsmodels=0.8.0
- conda-forge::altair=1.2.0
- conda-forge::dask-searchcv=0.0.2
- conda-forge::plotnine=0.2.1
- pip:
  - neo4j-driver==1.3.1
