name: cognoma-machine-learning
dependencies:
- jupyter=1.0.0
- numexpr=2.6.0
- numpy=1.11.1
- pandas=0.18.1
- python=3.5.2
- requests=2.11.1
- scikit-learn=0.17.1
- scipy=0.17.1
- seaborn=0.7.0
- statsmodels=0.6.1
- pip:
  - neo4j-driver==1.0.2
